spring:
  application:
    remoteHost: 192.168.31.46
    remotePort: 8787
    remoteAuthPort: 8181
    remoteGetStockNoSyncUrl: http://${spring.application.remoteHost}:${spring.application.remotePort}/api/inventory/v1/stock/getStockNoSync
    remoteModifyProductStateUrl: http://${spring.application.remoteHost}:${spring.application.remotePort}/api/inventory/v1/stock/modifyProductState/
    remoteModifyInventoryNumUrl: http://${spring.application.remoteHost}:${spring.application.remotePort}/api/inventory/v1/modifyInventoryNum/

    oauthUserName: user
    oauthPassword: password
    getTokenUrl: http://${spring.application.remoteHost}:${spring.application.remoteAuthPort}/uaa/oauth/token
    passwordGrantStr: ?grant_type=password&username=${spring.application.oauthUserName}&password=${spring.application.oauthPassword}
    accessTokenStr: ?access_token=
    oauthClientId: acme
    oauthSecret: acmesecret

    productIdKey: productId
    productNumKey: productNum
  profiles:
    active: development
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    demo : info
---
spring:
  profiles: development
  neo4j:
    host: 192.168.31.46
    port: 7474
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:neo4j}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: test
  neo4j:
    host: 192.168.31.46
    port: 8700