spring:
  application:
    remoteHost: 192.168.31.72
    remotePort: 8787
    remoteAuthPort: 8181
    remoteGetStockNoSyncUrl: http://${spring.application.remoteHost}:${spring.application.remotePort}/api/inventory/v1/stock/getStockNoSync
    remoteModifyProductStateUrl: http://${spring.application.remoteHost}:${spring.application.remotePort}/api/inventory/v1/stock/modifyProductState/
    remoteModifyInventoryNumUrl: http://${spring.application.remoteHost}:${spring.application.remotePort}/api/inventory/v1/modifyInventoryNum/

    oauthUserName: user
    oauthPassword: password
    getTokenUrl: http://${spring.application.remoteHost}:${spring.application.remoteAuthPort}/uaa/oauth/token
    passwordGrantStr: ?grant_type=password&username=${spring.application.oauthUserName}&password=${spring.application.oauthPassword}
    accessTokenStr: ?access_token=
    oauthClientId: acme
    oauthSecret: acmesecret

    productIdKey: productId
    productNumKey: productNum
  profiles:
    active: defult
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    demo : info