spring:
  profiles:
    active: defult
  application:
    description: common-service-description
    version: 0.0.1
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    demo: info

