spring:
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    demo: info
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://192.168.31.46:9999
    auth-service:
      path: /user/**
      url: http://192.168.31.46:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://192.168.31.46:8181/uaa/user
    client:
      accessTokenUri: http://192.168.31.46:8181/uaa/oauth/token
      userAuthorizationUri: http://192.168.31.46:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.31.46:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.31.46}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.31.46}:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.31.46}:8181/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:192.168.31.46}:8181/uaa/oauth/token
      userAuthorizationUri: http://${DOCKER_IP:192.168.31.46}:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

---

spring:
  profiles: test
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://192.168.31.46:9999
    auth-service:
      path: /user/**
      url: http://192.168.31.46:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://192.168.31.46:8181/uaa/user
    client:
      accessTokenUri: http://192.168.31.46:8181/uaa/oauth/token
      userAuthorizationUri: http://192.168.31.46:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.31.46:8761/eureka/