spring:
  profiles:
    active: test
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  level:
    demo: info
squid:
  demo:
    client:
      serviceName: payment-service
      dependencyServiceName: accountService
      dependencyServiceNamespace: squid.dataman.com
      sleepTime: 100
      serverSleepTime: 1
---
spring:
  profiles: development
  redis:
    host: localhost
    port: 6379
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://192.168.31.72:3306/dev?useSSL=false
    username: root
    password: dbpass
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
security:
  oauth2:
    resource:
      userInfoUri: http://192.168.31.72:8181/uaa/user
    client:
      client-id: acme
  ignored: /api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.31.72:8761/eureka/

---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://192.168.31.72:3306/dev?useSSL=false
    username: root
    password: dbpass
  jackson:
      date-format: "YYYY-MM-dd"
      serialization:
        write_dates_as_timestamps: true
security:
  oauth2:
    resource:
      userInfoUri: http://192.168.31.72:8181/uaa/user
    client:
      client-id: acme
  ignored: /api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.31.72:8761/eureka/

---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo
      port: 27017
  redis:
      host: localhost
      port: 6379
  mvc:
    date-format: "YYYY-MM-dd"
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://192.168.31.72:3306/dev?useSSL=false
    username: root
    password: dbpass
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.31.46}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/